# Naive Bayes

In [1]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Importing the dataset
data=pd.read_csv("phishing.csv")

In [3]:
data.shape

(11054, 32)

In [4]:
data.head()

Index  UsingIP  LongURL  ShortURL  Symbol@  Redirecting//  PrefixSuffix-  \
0      0        1        1         1        1              1             -1   
1      1        1        0         1        1              1             -1   
2      2        1        0         1        1              1             -1   
3      3        1        0        -1        1              1             -1   
4      4       -1        0        -1        1             -1             -1   

   SubDomains  HTTPS  DomainRegLen  ...  UsingPopupWindow  IframeRedirection  \
0           0      1            -1  ...                 1                  1   
1          -1     -1            -1  ...                 1                  1   
2          -1     -1             1  ...                 1                  1   
3           1      1            -1  ...                -1                  1   
4           1      1            -1  ...                 1                  1   

   AgeofDomain  DNSRecording  WebsiteTraffic  PageRank  GoogleIndex  \
0           -1            -1               0        -1            1   
1            1            -1               1        -1            1   
2           -1            -1               1        -1            1   
3           -1            -1               0        -1            1   
4            1             1               1        -1            1   

   LinksPointingToPage  StatsReport  class  
0                    1            1     -1  
1                    0           -1     -1  
2                   -1            1     -1  
3                    1            1      1  
4                   -1           -1      1  

[5 rows x 32 columns]

In [5]:
#deleting the index column
del data['Index']

In [6]:
data.shape

(11054, 31)

In [7]:
data.head()

UsingIP  LongURL  ShortURL  Symbol@  Redirecting//  PrefixSuffix-  \
0        1        1         1        1              1             -1   
1        1        0         1        1              1             -1   
2        1        0         1        1              1             -1   
3        1        0        -1        1              1             -1   
4       -1        0        -1        1             -1             -1   

   SubDomains  HTTPS  DomainRegLen  Favicon  ...  UsingPopupWindow  \
0           0      1            -1        1  ...                 1   
1          -1     -1            -1        1  ...                 1   
2          -1     -1             1        1  ...                 1   
3           1      1            -1        1  ...                -1   
4           1      1            -1        1  ...                 1   

   IframeRedirection  AgeofDomain  DNSRecording  WebsiteTraffic  PageRank  \
0                  1           -1            -1               0        -1   
1                  1            1            -1               1        -1   
2                  1           -1            -1               1        -1   
3                  1           -1            -1               0        -1   
4                  1            1             1               1        -1   

   GoogleIndex  LinksPointingToPage  StatsReport  class  
0            1                    1            1     -1  
1            1                    0           -1     -1  
2            1                   -1            1     -1  
3            1                    1            1      1  
4            1                   -1           -1      1  

[5 rows x 31 columns]

In [8]:
data.isnull().sum()

UsingIP                0
LongURL                0
ShortURL               0
Symbol@                0
Redirecting//          0
PrefixSuffix-          0
SubDomains             0
HTTPS                  0
DomainRegLen           0
Favicon                0
NonStdPort             0
HTTPSDomainURL         0
RequestURL             0
AnchorURL              0
LinksInScriptTags      0
ServerFormHandler      0
InfoEmail              0
AbnormalURL            0
WebsiteForwarding      0
StatusBarCust          0
DisableRightClick      0
UsingPopupWindow       0
IframeRedirection      0
AgeofDomain            0
DNSRecording           0
WebsiteTraffic         0
PageRank               0
GoogleIndex            0
LinksPointingToPage    0
StatsReport            0
class                  0
dtype: int64

In [9]:
x=data.iloc[:,:-1].values #Independent variables
y=data.iloc[:,30].values  #Dependent variables

In [10]:
print(x)

[[ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 [ 1  0  1 ...  1 -1  1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]]


In [11]:
print(y)

[-1 -1 -1 ... -1 -1 -1]


In [12]:
#Splitting the dataset into the Training and Test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [13]:
print(x_train)

[[ 1  1 -1 ...  1 -1  1]
 [ 1 -1  1 ...  1 -1  1]
 [ 1 -1  1 ...  1  1  1]
 ...
 [ 1 -1  1 ...  1  1  1]
 [ 1 -1  1 ...  1  0 -1]
 [ 1 -1  1 ...  1  0  1]]


In [14]:
print(y_train)

[1 1 1 ... 1 1 1]


In [15]:
print(x_test)

[[ 1 -1  1 ...  1  1  1]
 [ 1 -1  1 ...  1  0  1]
 [ 1  1  1 ...  1  0  1]
 ...
 [ 1 -1  1 ...  1  1 -1]
 [ 1 -1  1 ...  1  0  1]
 [ 1 -1  1 ...  1  1  1]]


In [16]:
print(y_test)

[ 1  1 -1 ...  1  1  1]


In [17]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [18]:
print(x_train)

[[ 0.72574341  2.12573205 -2.59206639 ...  0.39990904 -2.34805334
   0.40254308]
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904 -2.34805334
   0.40254308]
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904  1.14130082
   0.40254308]
 ...
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904  1.14130082
   0.40254308]
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904 -0.60337626
  -2.48420617]
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904 -0.60337626
   0.40254308]]


In [19]:
print(x_test)

[[ 0.72574341 -0.48015611  0.38579259 ...  0.39990904  1.14130082
   0.40254308]
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904 -0.60337626
   0.40254308]
 [ 0.72574341  2.12573205  0.38579259 ...  0.39990904 -0.60337626
   0.40254308]
 ...
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904  1.14130082
  -2.48420617]
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904 -0.60337626
   0.40254308]
 [ 0.72574341 -0.48015611  0.38579259 ...  0.39990904  1.14130082
   0.40254308]]


In [20]:
# Fitting classifier to the training set
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [21]:
# Predicting the test set result
y_pred=classifier.predict(x_test)
y_pred_train=classifier.predict(x_train)

In [22]:
#Making the confusion_matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [23]:
print(cm)

[[1181    1]
 [1148  434]]


In [24]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test, y_pred)

In [25]:
print(ac)

0.5842981186685963
